
// disclosures singleton hook keys, use to retrieve disclosures
export const CONNECT_WALLETS_DISCLOSURE = "CONNECT_WALLETS_DISCLOSURE"
export const SELECT_CHAIN_MODAL = "SELECT_CHAIN_MODAL"
export const SELECT_TOKEN_MODAL = "SELECT_TOKEN_MODAL"
export const SELECT_TOKEN_ADD_LIQUIDITY_MODAL = "SELECT_TOKEN_ADD_LIQUIDITY_MODAL"
export const SELECT_TOKEN_SWAP_MODAL = "SELECT_TOKEN_SWAP_MODAL"