export const CREATE_PAIR_FORMIK = "CREATE_PAIR_FORMIK"
export const ADD_LIQUIDITY_FORMIK = "ADD_LIQUIDITY_FORMIK"
export const SWAP_FORMIK = "SWAP_FORMIK"
export const CREATE_TOKEN_FORMIK = "CREATE_TOKEN_FORMIK"