export const GET_TOKEN_METADATA_SWR_MUTATION = "useGetTokenMetadataSwrMutation"
export const APTOS_MOVE_CALL_SWR_MUTATION = "useAptosMoveCallSwrMutation"
export const GET_POOL_METADATA_SWR = "useGetPoolMetadataSwr"
export const QUOTE_PRICE_OUT_SWR_MUTATION = "useQuotePriceOutSwrMutation"
export const GET_POOL_INFO_SWR = "useGetPoolInfoSwr"
export const GET_TOKEN_BALANCE_SWR = "useGetBalanceSwrMutation"
export const GET_LP_NFT_SWR = "useGetLPNFTSwrMutation"